@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Nov 29 14:49:58 +0700 2020
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim sequence_detector_tb_826_behav -key {Behavioral:sim_1:Functional:sequence_detector_tb_826} -tclbatch sequence_detector_tb_826.tcl -view D:/Ferris-Prima-Nugraha/HKUST/2020Fall/ELEC3310/miniproject_826/sequence_detector_tb_826_behav.wcfg -log simulate.log"
call xsim  sequence_detector_tb_826_behav -key {Behavioral:sim_1:Functional:sequence_detector_tb_826} -tclbatch sequence_detector_tb_826.tcl -view D:/Ferris-Prima-Nugraha/HKUST/2020Fall/ELEC3310/miniproject_826/sequence_detector_tb_826_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
